apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.deploy.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.app.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.app.serviceName }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.deploy.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Values.app.serviceName }}
    spec:
      containers:
        - name: {{ .Values.app.serviceName }}
          image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.app.otelEndpoint }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.app.serviceName }}
            - name: RUST_BACKTRACE
              value: "{{ .Values.app.backtraceEnabled }}"
          envFrom:
            - secretRef:
                name: mongodb-secret
          resources: {}
      restartPolicy: Always
status: {}