apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.deploy.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.app.serviceName }}
spec:
  # type: LoadBalancer
  ports:
    - name: "{{ .Values.app.port }}"
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      # nodePort: 30003
  selector:
    io.kompose.service: {{ .Values.app.serviceName }}
status:
  loadBalancer: {}
