apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truth-or-lie-cert
  namespace: dev
spec:
  secretName: truth-or-lie-tls
  renewBefore: 240h
  dnsNames:
    - truthorlie.info
    - www.truthorlie.info
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
